[FIX] product_configurator_sale: Missing dependency Otherwise the following is raised: in _get_order_line_vals     "customer_lead": product.sale_delay, AttributeError: 'product.product' object has no attribute 'sale_delay'